spring:
    datasource:
        url: jdbc:sqlite:sample.db
        driver-class-name: org.sqlite.JDBC
        username: pxp
        password: password
        hikari:
            maximum-pool-size: 1
            max-lifetime: 1800000
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
hibernate:
    hbm2ddl:
        auto: crete-drop
rest:
    tmdb:
        url: ${tmdb_url:https://api.themoviedb.org/3}
        token: ${tmdb_token:eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxNzc0Zjc1ZDI5MDFmNWY0YzQxZGIyMjE1OGE0OTlmNiIsInN1YiI6IjY1NTgwNWE4ZWE4NGM3MTA5NmRlNjY5MSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.OTSmovVYpYKJMydsxtRGs5I6JnSMCp6qMNjcYLyLedA}
        key: ${tmdb_key:1774f75d2901f5f4c41db22158a499f6}
